[project]
name = "tiny-worker"
version = "0.1.0"
description = "A tiny utility for easy paralellism in Python."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = ["ipykernel>=6.29.5", "ipywidgets>=8.1.5", "ruff>=0.9.2"]

[tool.ruff]
line-length = 120
